### ISSUE TITLE
UPX worthiness

### ISSUE THREAD

**Issue by mathieu-aubin** [wader/static-ffmpeg#128]
Have you played with UPX at all? I figure it sometimes GREATLY reduces my binaries but sometimes, without having any knowledge of how (truly), it makes them almost unusable even thoe they run correctly at facevalue. Maybe worth investigating...

**Comment by mathieu-aubin** [comment]
It would probably require a full set of test for each library... which wouldnt be such a bad idea in the grand scheme of things.

**Comment by wader** [comment]
Nope only heard of it but never used it. Is is known to cause issues?

Yes some kind of tests could be nice (even without UPX). What would you like to test? encode/decode with various libs? one could also run ffmpeg fate.

**Comment by mathieu-aubin** [comment]
no idea about ffmpeg fate and no idea either about which tests could be reliable. It could be left to uses to find bugs but that can cause issues with integration at a later date for you. Regressions and such. UPX is great and as far as i know, is not known to cause issues. It does slow up start times tho. But it compresses binaries ALOT.

Maybe only worth for when yuo download the thing but if you use it enough, in the long run, the longer start time will bite you back. Maybe offer a choice when compiling, maybe dismiss this altogether? Just a thought about UPX.

**Comment by wader** [comment]
Ok will think about it. In my use cases it has not been a concern that the binaries are quite large (in some projects they are small compared to other things in the image :). At least docker will compress the images quite well, latest it 60MB compressed 160MB uncompressed.

**Comment by mathieu-aubin** [comment]
> What about UPX? If you’re not familiar with UPX, it’s an amazing tool that reduces the size of binaries. It does so by compressing the binary, and adding a small stub to uncompress and run it transparently. If we want to reduce the footprint of our containers, UPX will also be very counter-productive. First, the disk and network usage won’t be reduced a single bit, since layers are compressed anyway; so UPX won’t get us anything here.

from https://www.ardanlabs.com/blog/2020/04/docker-images-part3-going-farther-reduce-image-size.html

**Comment by wader** [comment]
Thanks, adding to reading list!

**Comment by mathieu-aubin** [comment]
docker-slim seems interresting. maybe not here but in general.
