### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by mathieu-aubin** [wader/static-ffmpeg#131]
`Step 102/151 : COPY --from=cargo-c /usr/local/cargo/bin/cargo-c* /usr/bin
When using COPY with more than one source file, the destination must be a directory and end with a /
`
this seems new. at least i never seen this.

**Comment by mathieu-aubin** [comment]
simple fix i believe, and yes, it works when editing proper line in Dockerfile

**Comment by mathieu-aubin** [comment]
also...

`Step 103/151 : RUN   OPENSSL_VERSION=$(pkg-config --modversion openssl)   LIBXML2_VERSION=$(pkg-config --modversion libxml-2.0)   EXPAT_VERSION=$(pkg-config --modversion expat)   FREETYPE_VERSION=$(pkg-config --modversion freetype2)    FONTCONFIG_VERSION=$(pkg-config --modversion fontconfig)    FRIBIDI_VERSION=$(pkg-config --modversion fribidi)    SOXR_VERSION=$(pkg-config --modversion soxr)   FFTW_VERSION=$(pkg-config --modversion fftw)   LIBSAMPLERATE_VERSION=$(pkg-config --modversion samplerate)   jq -n   '{   ffmpeg: env.FFMPEG_VERSION,   openssl: env.OPENSSL_VERSION,   libxml2: env.LIBXML2_VERSION,   expat: env.EXPAT_VERSION,   libmp3lame: env.MP3LAME_VERSION,   libtwolame: env.TWOLAME_VERSION,   "libfdk-aac": env.FDK_AAC_VERSION,   libogg: env.OGG_VERSION,   libvorbis: env.VORBIS_VERSION,   libopus: env.OPUS_VERSION,   libtheora: env.THEORA_VERSION,   libvpx: env.VPX_VERSION,   libx264: env.X264_VERSION,   libx265: env.X265_VERSION,   libwebp: env.LIBWEBP_VERSION,   libspeex: env.SPEEX_VERSION,   libvmaf: env.VMAF_VERSION,   libaom: env.AOM_VERSION,   libvidstab: env.VIDSTAB_VERSION,   libkvazaar: env.KVAZAAR_VERSION,   libfreetype: env.FREETYPE_VERSION,   fontconfig: env.FONTCONFIG_VERSION,   libfribidi: env.FRIBIDI_VERSION,   libass: env.LIBASS_VERSION,   libzimg: env.ZIMG_VERSION,   libsoxr: env.SOXR_VERSION,   libopenjpeg: env.OPENJPEG_VERSION,   libdav1d: env.DAV1D_VERSION,   libxvid: env.XVID_VERSION,   librav1e: env.RAV1E_VERSION,   libsrt: env.SRT_VERSION,   libsvtav1: env.SVTAV1_VERSION,   libdavs2: env.DAVS2_VERSION,   libxavs2: env.XAVS2_VERSION,   libmodplug: env.LIBMODPLUG_VERSION,   libuavs3d: env.UAVS3D_COMMIT,   libmysofa: env.LIBMYSOFA_VERSION,   libsamplerate: env.LIBSAMPLERATE_VERSION,   librubberband: env.RUBBERBAND_VERSION,   fftw: env.FFTW_VERSION,   }' > /versions.json
 ---> Running in ad3b7fdafe06
Package fftw was not found in the pkg-config search path.
Perhaps you should add the directory containing `fftw.pc'
to the PKG_CONFIG_PATH environment variable
Package 'fftw', required by 'virtual:world', not found
`

**Comment by mathieu-aubin** [comment]
seems like it's /usr/lib/pkgconfig/fftw3.pc now.
from https://pkgs.alpinelinux.org/contents?file=&path=&name=*fftw*&branch=v3.14&repo=main&arch=x86

**Comment by mathieu-aubin** [comment]
Also... maybe qt-faststart isn't needed overall... i know i was the one to push for it a while back but i don't actually use it. it's simple enough to use `-movflags +faststart` that it makes it a bit useless.

**Comment by wader** [comment]
The fftw issue error didn't break the build or was the file renamed just recently?

**Comment by wader** [comment]
I haven't had a need for qt-faststart in a while so ok to remove for me. The binary seems to be about the same size as ffmpeg/ffprobe.

btw i did a hack once for ffmpeg to introduce a "fftool" that was a combination of ffmpeg/ffprobe and then it behaved differently depending on argv[0]. That would save some space. But one problem i think was that docker COPY did not understand symlink and hardlinks :(

**Comment by mathieu-aubin** [comment]
> The fftw issue error didn't break the build or was the file renamed just recently?

it did break my own builds when i tried on CentOS7 with the newest (at the time) master - i found it somewhat weird but it might have been that my docker updated, i can't say.

> btw i did a hack once for ffmpeg to introduce a "fftool" that was a combination of ffmpeg/ffprobe and then it behaved differently depending on argv[0]. 

Could you find a way to show me? Don't waste your time on it but... it's interresting and i _might_ be able to help

**Comment by mathieu-aubin** [comment]
i wonder if we could hack the presets for mp4 to add fasstart as default. thought experiment - i'm no ffmpeg or even anything else expert. Just a sysadmin in search of more challenges

**Comment by wader** [comment]
> Could you find a way to show me? Don't waste your time on it but... it's interresting and i _might_ be able to help

Found an old branch with it https://github.com/wader/FFmpeg/commit/935d3fd546f1b2a666458eb49bcdaa3b9bbf132a but i dont think it will work with docker sadly, a bit too many hacks and hard to maintain and not sure it's upstreamable.

**Comment by wader** [comment]
> i wonder if we could hack the presets for mp4 to add fasstart as default. thought experiment - i'm no ffmpeg or even anything else expert. Just a sysadmin in search of more challenges

Mm but think i would be reluctant to change ffmpeg defaults

**Comment by mathieu-aubin** [comment]
> ut i dont think it will work with docker sadly, a bit too many hacks and hard to maintain and not sure it's upstreamable.

thats fine. docker is kinda new to me, i used to go the long route and build custom machines using kvm which would take forever

i wonder why faststart isn't default. I guess i could/should educate myself.

**Comment by mathieu-aubin** [comment]
> -movflags faststart
Run a second pass moving the index (moov atom) to the beginning of the file. This operation can take a while, and will not work in various situations such as fragmented output, thus it is not enabled by default.

as per https://www.bogotobogo.com/VideoStreaming/ffmpeg_AdaptiveLiveStreaming_SmoothStreaming.php

**Comment by mathieu-aubin** [comment]
also, here is my latest build record, if of any interrest
https://asciinema.org/a/K2YNtqy8mxjbuDNLoTllPMEfb
