### ISSUE TITLE
Build multi-arch images on AWS spot instances

### ISSUE THREAD

**Issue by pldin601** [wader/static-ffmpeg#158]
The discussion begins here: https://github.com/wader/static-ffmpeg/pull/157

> But i guess it's a bit of a balance, having just one multi-arch image would be quite neat also and very clean and simple for users of the image. So in summary for me i think it's a good idea be allow hacky things inside the Dockerfile to do whatever is needed to produce static binaries but be cautious with complicated things in CI and build env etc?

@wader Maybe it's better to make PR on target libraries for helping them to compile on not only on x86_64 arch instead of hacking the Dockerfile?

To be honest, spawning two parallel universes to build the library on them, looks for me overkill. It's a very interesting challenge for me as an engineer, but it will make things more complicated to maintain.

**Comment by wader** [comment]
> The discussion begins here: #157
> 
> > But i guess it's a bit of a balance, having just one multi-arch image would be quite neat also and very clean and simple for users of the image. So in summary for me i think it's a good idea be allow hacky things inside the Dockerfile to do whatever is needed to produce static binaries but be cautious with complicated things in CI and build env etc?
> 
> @wader Maybe it's better to make PR on target libraries for helping them to compile on not only on x86_64 arch instead of hacking the Dockerfile?

Yes that is what i've usually done, file issues or send patch upstream and then maybe do hacks temporary. The things that usually cause issues is the uncommon combination of using musl and linking as static PIE.

> To be honest, spawning two parallel universes to build the library on them, looks for me overkill. It's a very interesting challenge for me as an engineer, but it will make things more complicated to maintain.

Think i agree, for now i rather have one Dockerfile for everything with sed-hacks etc then multiple repos or branches. And i don't think it will be a problem as long as we build each arch native or emulated compared to cross compile C code which is usually a mess.

**Comment by pldin601** [comment]
It started to work.

Here's the example of successful run:

https://github.com/myownradio/static-ffmpeg/actions/runs/1823775383

and the workflow file looks like this:

https://github.com/myownradio/static-ffmpeg/blob/feat/spot-ci/.github/workflows/spot-test.yml

Here's the resulting image:

https://hub.docker.com/layers/144179126/pldin601/static-ffmpeg/latest/images/sha256-46cf4f9bceef46483aecadb246187f6324738a532616e9650d941fef85e05c69?context=repo

**Comment by wader** [comment]
@pldin601 very interesting stuff. Still wonder if it would be possible to package something like this as github action step thingy, like make it nearly transparent compared to using standard docker step containers. And how is that compared to using own action runner hosts

**Comment by pldin601** [comment]
@wader It's rather an experimenting thing. Not sure what the steps for making it simple as single package of GitHub action should be performed. It's possible to spawn spots with pre-installed GitHub runners and using them for running other steps instead of connecting with SSH. But we still need to perform terraform actions before and after build. Also, AWS has its own limitations and quotes. For example, it limits me how many spots I can spawn per hour(?). And I need to wait a few hours before I can be able to spawn instances again.

**Comment by wader** [comment]
Closed by #159
