### ISSUE TITLE
x11grab/xcbgrab

### ISSUE THREAD

**Issue by brunobg** [wader/static-ffmpeg#173]
Would it be possible to support x11grab/xcbgrab?

**Comment by wader** [comment]
Hi, i looks like alpine has a static package for the dependency needed https://pkgs.alpinelinux.org/package/v3.15/main/armhf/libxcb-static. Maybe you could try build an image with support and try how it works?

**Comment by wader** [comment]
@brunobg hi,, did you end up testing something?

**Comment by wader** [comment]
Closing for now as i don't think i will look into it, feel free to reopen if someone does.
