### ISSUE TITLE
[feat] amqp support ?

### ISSUE THREAD

**Issue by Gounlaf** [wader/static-ffmpeg#185]
Hi,

Are you OK to add AMQP support?
I can make a PR :)

Regards.

**Comment by wader** [comment]
Sure! plan to use the rabbitmq-c-dev alpine package if it has static archives or build ourself? didn't see any .a files in the -dev package, but i might have missed something. Also maybe good to know that the alpine people are usually very quick at adding -static package if you file an issue about it.

Also feel free to add documentation to the README if there is something amqp specific that might be useful to know.

**Comment by Gounlaf** [comment]
If I'm right, there is no static package available, and the latest version of _librabbitmq_ is only available in **edge**

**Comment by Gounlaf** [comment]
I just need to figure out how the "bump script" works
And need to retrieve the shasum of archive. I'm not sure there is a "official" one provided

**Comment by wader** [comment]
Okok, the [rabbitmq-c-dev](https://pkgs.alpinelinux.org/packages?name=rabbitmq-c-dev&branch=v3.15) package seems to be available in stable but see no .a-archives in it... the build script seems to explicitly remove them https://git.alpinelinux.org/aports/tree/main/rabbitmq-c/APKBUILD?h=3.15-stable#n36, weirdly enough just above it builds with `-DBUILD_STATIC_LIBS=ON` :) i think we can file an issue and they will add a -static package, i've done that multiple times. But we can build from source for now if you don't want to wait.

**Comment by Gounlaf** [comment]
It can wait. I'm using your complete Dockerfile with the additions provided in the PR; except I sync manually from yours times to times

**Comment by wader** [comment]
👍  Filed and issue about it https://gitlab.alpinelinux.org/alpine/aports/-/issues/13751

**Comment by wader** [comment]
I'm ok with merging as it is now also. Even if fixed fast I think it might take until next alpine stable release for a -static package to show up

**Comment by Gounlaf** [comment]
As you wish @wader.

Also, I'm not an expert in library building. It took me a lot of tries - when I first set it up, long time ago xD - to find correct path and parameters to the CMake command. E.g I don't remember why I had to put `-DCMAKE_INSTALL_PREFIX=/usr/local` whereas alpine provide set it as `-DCMAKE_INSTALL_PREFIX=/usr` :thinking: 

So, if I may, take the time to double check :worried:

**Comment by wader** [comment]
No worries. I might see i can simplify something but i think it looks good.

**Comment by wader** [comment]
Fixed by #186

**Comment by wader** [comment]
btw a bit curious, how do you use amqp with ffmpeg? i work with transcoding systems so interesting to know how people build stuff

**Comment by Gounlaf** [comment]
Can only answer in private 😅

**Comment by wader** [comment]
Alpine issue was fixed some days ago so we could use that package (same version as we use now 0.11.0) once there is a new stable release https://gitlab.alpinelinux.org/alpine/aports/-/issues/13751
