### ISSUE TITLE
Cannot resolve another docker container hostname

### ISSUE THREAD

**Issue by SuperCuber** [wader/static-ffmpeg#229]
I'm trying to `ffmpeg -i http://other_container` but it cannot resolve the hostname.
```
/app # ping server
PING server (172.23.0.4): 56 data bytes
64 bytes from 172.23.0.4: seq=0 ttl=64 time=0.068 ms
drill64 bytes from 172.23.0.4: seq=1 ttl=64 time=0.073 ms
^C
--- server ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.068/0.070/0.073 ms
/app # apk add drill
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ldns (1.7.2_git20210911-r1)

;; ANSWER SECTION:
server. 600     IN      A       172.23.0.4

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Thu Aug  4 09:51:48 2022
;; MSG SIZE  rcvd: 46
/app # ffmpeg -i http://server/
ffmpeg version 4.4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disabl
e-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable
-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrn
b --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --e
nable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libweb
p --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[tcp @ 0x5df1640] Failed to resolve hostname server: System error
http://server/: Input/output error
```

I'm not sure what to do here... I remember having a similar problem with nginx that was solved by changing the configuration, but I don't know how to apply that here.

In the meanwhile I'm using a different image `tnk4on/yt-dlp:alpine-pip` instead of `tnk4on/yt-dlp:alpine-static` and that seems to fix the issue.

**Comment by wader** [comment]
Hi, looking at the ffmpeg version output it looks like the binary is from https://johnvansickle.com/ffmpeg/? it's a similar project to this. Maybe move it here?

But that said i've had DNS issue with alpine myself when the DNS response was very large (it does not support DNS over TCP). Maybe try `ffmepg -v trace` for more verbose output, also maybe see if `netcat` or some other non-network debug tool can resolve. Also a bit suspicious that this seems to be static binary build on debian (glibc) but is running in alpine (musl libc). Could be NSS issues etc? you could try a binary from this project which is build statically with musl.

**Comment by SuperCuber** [comment]
Ah I see. I assumed it was using this project, my bad :)

Netcat resolves the hostname just fine. Very strange, and based on `drill`s output it doesn't look like the dns response is too large - just one record. I can't find an issue board for johnvansickle's project and I solved my own issue so I don't think I'm going to keep debugging this. TY for the swift response though :D

**Comment by wader** [comment]
No problem, what was the issue or solved it some other way?

**Comment by SuperCuber** [comment]
I switched to `tnk4on/yt-dlp:alpine-pip` instead of `tnk4on/yt-dlp:alpine-static`, which uses a different ffmpeg with
```
  built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027
```

**Comment by wader** [comment]
Ok, that seems to use ffmpeg from alpine. I suspect some kind of glibc NSS issue with alpine-static, static glibc is messy.

**Comment by mathieu-aubin** [comment]
Try installing 'nscd' to fix dns resolution issues for binaries compiled using  static glibc. Its probably installed in the container already, in the one that works fine.
