### ISSUE TITLE
libxvid available in alpine repositories

### ISSUE THREAD

**Issue by Gounlaf** [wader/static-ffmpeg#25]
Hi,

It seems that xvid is available in [alpine repositories](https://pkgs.alpinelinux.org/packages?name=xvidcore-static&branch=edge).
Should it be used instead of compiling from source?

**Comment by wader** [comment]
Hello, mm maybe, what libraries i build from source and what i install from alpine have is vaguely based on this:
- Do the package exists in alpine?
- Is there a static package? if not file bug to get it added (they are very friendly as fast to add)
- Do i want to wait for alpine for version updates?
- How important is it that the libraries is built with hardened options?

Also i've leaned towards building codec libraries from source as they are probably the  updated i want the most and it's nice to use https://github.com/wader/bump to automate most of it. Guess i could add alpine package version support to bump to automate also.

Is there particular reason you want to use the alpine package version of libxvid?

**Comment by Gounlaf** [comment]
> Is there particular reason you want to use the alpine package version of libxvid?

Not really. I needed a custom ffmpeg and found your repo.

* I just wonder why some where from alpine, or from source -> you answered it :)
* I've noticed during compilation time that flag/options `--enable-static` and `--disable-shared` (from Dockerfile#L318) are not supported

**Comment by wader** [comment]
Aha now i  see, you mean the `configure: WARNING: unrecognized options: --enable-static, --disable-shared` warning when building xvid? mm should look into that. Guess default it builds both? should probably also make sure it uses the hardened flags.

Good you noticed!

**Comment by Gounlaf** [comment]
> Aha now i see, you mean the `configure: WARNING: unrecognized options: --enable-static, --disable-shared` warning when building xvid?

Exactly :)

**Comment by wader** [comment]
Fixed in c4b5c7fbffda5e353f3e0c3e46a327ed8dc18acd. Didn't find any way of disable shared but should be ok as we only use the static one anyways. Also went thru most libraries to see how they use CFLAGS and noticed that xvid was actually missing som optimization flags when CFLAGS was set.

**Comment by wader** [comment]
Close?

**Comment by Gounlaf** [comment]
@wader I think you can. Thanks.

**Comment by wader** [comment]
Ok! thanks again and hope the docker image is useful!
