### ISSUE TITLE
Caching research

### ISSUE THREAD

**Issue by binoculars** [wader/static-ffmpeg#252]
After some tweaks and [enabling caching](https://github.com/binoculars/ffmpeg-build-lambda/commit/490f73f8382a91b27e5ba6fcaee399b2aba024e7), I was able to get the build down to [10 minutes](https://github.com/binoculars/ffmpeg-build-lambda/actions/runs/3200809710/jobs/5228139505) for an added library (libsnappy) and 1 minute for non-Dockerfile changes. Updating x265 took about [17 minutes](https://github.com/binoculars/ffmpeg-build-lambda/actions/runs/3200886376/jobs/5228299959). I think this is the way to go for speed.

### What I did to my repo:
- Move most ARGs to the top
- Inherit ARGs only where needed
- Enable caching for GitHub actions docker builds
- Parallelize the builds by breaking them up into multi-stage
- Use COPY command to copy only files needed from previous stages
- Added several new libraries

**Comment by wader** [comment]
> After some tweaks and [enabling caching](https://github.com/binoculars/ffmpeg-build-lambda/commit/490f73f8382a91b27e5ba6fcaee399b2aba024e7), I was able to get the build down to [10 minutes](https://github.com/binoculars/ffmpeg-build-lambda/actions/runs/3200809710/jobs/5228139505) for an added library (libsnappy) and 1 minute for non-Dockerfile changes. Updating x265 took about [17 minutes](https://github.com/binoculars/ffmpeg-build-lambda/actions/runs/3200886376/jobs/5228299959). I think this is the way to go for speed.

Interesting, thanks for trying things out!

> ### What I did to my repo:
> * Move most ARGs to the top

It actually used to be like that but at some point i decided it was nice to not spread things out if possible

> * Inherit ARGs only where needed
> * Enable caching for GitHub actions docker builds
> * Parallelize the builds by breaking them up into multi-stage
> * Use COPY command to copy only files needed from previous stages
> * Added several new libraries

**Comment by wader** [comment]
Wops accidentlly submitted above comment before i was done writing...  editing now :)

**Comment by binoculars** [comment]
The cache limits for gha are currently 10 GB and 7 days which seems pretty reasonable.

Not sure about the .so files—I haven’t tested these features yet, although I had frei0r in an old build.

Yes libcaca failed on the build but not configure, so I tried pushing that while testing it failed so I had to remove it.

**Comment by wader** [comment]
Adding caching https://github.com/wader/static-ffmpeg/pull/253. Not as useful without more stages but much better than nothing

**Comment by wader** [comment]
BTW know if there are any security concern with using a shared cache between PR and other builds? if content addressable i would guess not?

**Comment by binoculars** [comment]
Not that I'm aware of. Works like a charm if you only build master branch, but I'm just too paranoid to let it build without a manual review first.

**Comment by wader** [comment]
Ok, will probably sync some other things from your fork when i get time, thanks again for working on it! let's keep in touch!
