### ISSUE TITLE
Use xvidcore-static package from alpine

### ISSUE THREAD

**Issue by mathieu-aubin** [wader/static-ffmpeg#265]
https://github.com/wader/static-ffmpeg/blob/9ec48502732579e0db3cd02e44d5d2c3cc8233b0/Dockerfile#L712

there is a package for xvidcore-static in alpine, maybe of help in reducing build time...

https://git.alpinelinux.org/aports/tree/community/xvidcore/APKBUILD

**Comment by wader** [comment]
Thanks, good to know. I guess there wont be any new releases any time soon, so only reason to build ourselves would be the hardening but not sure that is worth it.

**Comment by mathieu-aubin** [comment]
Maybe check this out, too...

https://pkgs.alpinelinux.org/contents?file=*.a&path=&name=*static*&branch=edge&arch=x86_64

**Comment by wader** [comment]
Nicer query 😎

**Comment by wader** [comment]
Spring cleaning, revisit if there are any issues related to xvid
