### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by fasihi01-duplicate** [wader/static-ffmpeg#305]
Hi 

the following line fails since tonight:

$ echo "0644d73d4dcb8171c465334dba891b0965311f9ec66b1987805c2882afa0cc58  libssh.tar.gz" | sha256sum -c -
libssh.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

I have no clue why and how to fix, maybe it will fix itself somehow in the next days, please just have a look.

Thank you!

**Comment by fasihi01-duplicate** [comment]
Yes you're right, the issue is resloved. Thank you for the headsup.

**Comment by wader** [comment]
👍  no worries, let me know if it happen again, maybe we can figure out some way to make it more stable
