### ISSUE TITLE
AOMediaCodec requires login

### ISSUE THREAD

**Issue by fasihi01** [wader/static-ffmpeg#380]
Hi,

the wget to 
https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.8.0/SVT-AV1-v1.8.0.tar.bz2 
has moved behind a github login since 16th of december. So on my external gitlab, i can not build ffmpeg anymore.
Is this something that you want to address, or is it rather my todo?

Thank you and best regards,

Tobias

**Comment by wader** [comment]
Hey! that would be bad and i also use this project in a private non-github-CI system. But could it have been something temporary? when i try from my home laptop it seems to download without login:
```sh
$ curl -sL https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.8.0/SVT-AV1-v1.8.0.tar.bz2 | tar t | head -5
SVT-AV1-v1.8.0/
SVT-AV1-v1.8.0/.clang-format
SVT-AV1-v1.8.0/.gitignore
SVT-AV1-v1.8.0/.gitlab-ci.yml
SVT-AV1-v1.8.0/.gitlab/
```

Have log or can get verbose log from when it happens?

**Comment by fasihi01** [comment]
Ok you're right, funnily now it goes without login. My build still fails, but i have to investigate, see below. Do you have a hint? 

If not please feel free to close this issue.

Thank you very much for your time & effort!

 > [builder 31/49] RUN   wget --retry-on-host-error --retry-on-http-error=429,500,502,503 -O svtav1.tar.bz2 "https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.8.0/SVT-AV1-v1.8.0.tar.bz2" &&   echo "a7a8940a310a975ea953397ccb5b4167daf06e5e933ada6610fcb5db99491054  svtav1.tar.bz2" | sha256sum --status -c - &&   tar --no-same-owner --extract --file svtav1.tar.bz2 &&   cd SVT-AV1-*/Build &&   cmake     -G"Unix Makefiles"     -DCMAKE_VERBOSE_MAKEFILE=ON     -DCMAKE_INSTALL_LIBDIR=lib     -DBUILD_SHARED_LIBS=OFF     -DCMAKE_BUILD_TYPE=Release     .. &&   make -j$(nproc) install:
0.925   9050K .......... .......... .......... .......... ..........  109M
0.929   9300K .......... .......... .......... .......... .......... 54.5M
0.930   9350K .......... .                                            139M=0.2s
0.930 
0.930 2023-12-19 10:06:56 (53.9 MB/s) - 'svtav1.tar.bz2' saved [9585789]
0.930 
------
ERROR: failed to solve: executor failed running [/bin/sh -c wget $WGET_OPTS -O svtav1.tar.bz2 "$SVTAV1_URL" &&   echo "$SVTAV1_SHA256  svtav1.tar.bz2" | sha256sum --status -c - &&   tar $TAR_OPTS svtav1.tar.bz2 &&   cd SVT-AV1-*/Build &&   cmake     -G"Unix Makefiles"     -DCMAKE_VERBOSE_MAKEFILE=ON     -DCMAKE_INSTALL_LIBDIR=lib     -DBUILD_SHARED_LIBS=OFF     -DCMAKE_BUILD_TYPE=Release     .. &&   make -j$(nproc) install]: exit code: 1

**Comment by wader** [comment]
Think i know what has happened now : bump found the new v1.8.0 tag a week ago https://github.com/wader/static-ffmpeg/pull/377 but then some days ago the v1.8.0 tag was modified to include a "Added missing licenses in multiple neon files" commit https://gitlab.com/AOMediaCodec/SVT-AV1/-/commits/v1.8.0/?ref_type=tags

I'll do a PR to update the sha sum

**Comment by wader** [comment]
Tried to find if svtav1 has something more stable but seems they don't package any archives https://gitlab.com/AOMediaCodec/SVT-AV1/-/releases the "assets" there i think points to git tags?

Maybe not a big deal, shouldn't happen that often, and good to know that the checksumming works :) but it would be nice if the log was clearer about what failed hmm

**Comment by fasihi01** [comment]
My pipeline is fixed again, thank you very much!
