### ISSUE TITLE
ffmpeg: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Svyatk0** [wader/static-ffmpeg#417]
Hiya. 

Thanks for the amazing work that went in to this project. - monumental !!

Building and running form the latest Master when starting the container i get shared library error
`ffmpeg   | ffmpeg: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`
 
going over the Dockerfile i cant see anything pointing at it being shared. 

Any clues would be appreciated

svyatko

**Comment by wader** [comment]
Hey! thanks

That is strange, are you building the image yourself or using mwader/static-ffmpeg:latest? no modifications to the Dockerfile? if possible can you give examples or step to reproduce?

**Comment by Svyatk0** [comment]
Hey. 
Very strange indeed, hence i thought I'd check with you. 
I am building the image myself. ,My environment is ubuntu 22.04
i am going with a simple manual process: 
git clone https://github.com/wader/static-ffmpeg.git
cd static-ffmpeg
sudo docker-compose build
sudo docker-compose up

which results in the above error. 
I have made no changes to the Dockerfile as yet. wanted to make sure its up and running before trimming few things out. 
 
Cheers

Svyatko

**Comment by wader** [comment]
Can you share your compose config? wondering if it ends up running some other or older image

Does this work?
```
docker build -t test .
docker run test
```

**Comment by Svyatk0** [comment]
You were spot on. the compose was using a previous image where i had issues with fontconfig. 
Thank you very much for the help and all the hard work setting this up. 

I will close the issue

**Comment by wader** [comment]
👍 no problem!
