### ISSUE TITLE
--enable-libharfbuzz missing

### ISSUE THREAD

**Issue by nywhere** [wader/static-ffmpeg#429]
Hi,

First, thanks for this repo. Really useful.

I have noticed drawtext filter is not working. Launching the following command:

`docker run -i --rm -u $UID:$GROUPS -v "$PWD:$PWD" -w "$PWD" -v /tmp:/tmp mwader/static-ffmpeg:7.0  -i /tmp/source.mp4 -vf drawtext="fontsize=30:fontfile=/tmp/font.ttf:text='hello world':x=(w-text_w)/2:y=(h-text_h)/2" -c:v libx264   video.mp4
`
will fail with:

[AVFilterGraph @ 0xffff805a7030] No such filter: 'drawtext'
[vost#0:0/libx264 @ 0xffff805a6050] Error initializing a simple filtergraph

Adding `  --enable-libharfbuzz \  ` to the docker file would fix it.

I have built it locally and the following command executes properly:

`
docker run -i --rm -u $UID:$GROUPS -v "$PWD:$PWD" -w "$PWD" -v /tmp:/tmp ffmpeg  -i /tmp/source.mp4 -vf drawtext="fontsize=30:fontfile=/tmp/font.ttf:text='hello world':x=(w-text_w)/2:y=(h-text_h)/2" -c:v libx264   video.mp4
`

**Comment by wader** [comment]
Hey! of course, weird i must have forgotten to add it as we already install harfbuzz libraries during build
