### ISSUE TITLE
platform tags missing

### ISSUE THREAD

**Issue by klausbadelt** [wader/static-ffmpeg#439]
Hi @wader - first of all, thank you for your brilliant work.

As of ~last week, image(s) on Docker Hub with tags including the architecture - specifically `mwader/static-ffmpeg:6.1.1-arm64` - seem missing. Only `mwader/static-ffmpeg:6.1.1` now seems left. `latest` still has arch names in the tag, though.

This broke our CI (yeah I know, we could just build our own, but... ;-) ). 

Are you planning on removing tags with arch name permanently from now on?

**Comment by wader** [comment]
Wow you have composed music for lots movie and other things? i'm a big Werner Herzog fan btw :)

**Comment by klausbadelt** [comment]
Hi there! Thanks for the kind words. I'll let Werner know next time :) 

Our team had probably misunderstood that each arch has its own tag. Using multi-arch images is no problem, now that we understand. Thanks for clarifying.

**Comment by wader** [comment]
> Hi there! Thanks for the kind words. I'll let Werner know next time :)

🥳

> Our team had probably misunderstood that each arch has its own tag. Using multi-arch images is no problem, now that we understand. Thanks for clarifying.

Great! it will also simplify things if you ever start sharing Dockerfile:s between hosts running on different archs.
