### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by famda** [wader/static-ffmpeg#448]
Hi,
I'm trying to use your docker images to test something here but I'm having some issue. 
Based on your readme, I've used this inside my dockerfile:

``` docker
COPY --from=mwader/static-ffmpeg:7.0-2 /ffmpeg /usr/local/bin/
COPY --from=mwader/static-ffmpeg:7.0-2 /ffprobe /usr/local/bin/
```

but when I EXEC inside my built image, there's nothing on those folders.
Can you help, please? Maybe I'm doing something wrong.

Thanks in advance

**Comment by famda** [comment]
I know what the issue is. closing.
Awesome work!

**Comment by wader** [comment]
👍 was it some gotcha that could be added to the readme?

**Comment by famda** [comment]
Not really, my dockerfile has a multistage build and I was not copying the folders between stages.
My mistake. :D

**Comment by wader** [comment]
I see 👍 thanks for replying
