### ISSUE TITLE
AVX512 not working with x265 or svt-av1 codecs

### ISSUE THREAD

**Issue by phpb-com** [wader/static-ffmpeg#483]
I've tried to run this ffmpeg on a system with AVX512 and found that neither x265 nor svt-av1 are using it. I was able to make svt-av1 use it after adding `-DENABLE_AVX512=ON` to the Dockerfile (to the compilation flags of svt-av1) but was not able to make x265 use or detect it. Do you know of any reasons why that might be the case with x265?

**Comment by wader** [comment]
Hey, huh nice find! i guess at the time i assumed it would be feature detected. I see in build log that some other libs and ffmpeg do detect and i hope build with avx512.

So yes it would be great to add this if it needs to be done explicitly in some places. I wonder if it needs to be done conditionally only for amd64? also for svt-av1 the cmake has AVX512 stuff but for x265 i don't find much about `asm=avx512`, do you know if it's documented etc somewhere? ...also are there more cpu features we should enable in some libs?

About breaking, good question. I did a quick search what kind of support one can expect on half-modern cpus but was not clear, seems there are subsets of AVX-512? i also wonder if ffmpeg and libs usually runtime detect even if built with it?

**Comment by wader** [comment]
Aha now i see, you mean for x265 i do build with avx512 but it need to be enabled at runtime with `-x265-params`? if so can it be made default or is there some reason it's not default?

Sorry for feature creeping this issue, probably good to focus on fixing just avx512 for x265 and svt-av1 first. Can look at other stuff later.

Please do a draft PR if you like. It's a bit late here but can have a look at it also tomorrow

**Comment by wader** [comment]
I guess for x265 it could be mentioned in the README that it's possible

**Comment by wader** [comment]
Close issue? svt1-av1 is now built with avx512 and as i understand x265 can use avx512 awith an option
