### ISSUE TITLE
RUST static link symbols collision

### ISSUE THREAD

**Issue by examedia-video-engineering** [wader/static-ffmpeg#501]
chekdupsym has found a symbol duplicate, any way to avoid that please? Prefereably without rewriting all rust libs )

**Comment by examedia-video-engineering** [comment]
I added libzmq to the build it seem to have collision?

libssh.a:sha1_init
libzmq.a:sha1_init

**Comment by wader** [comment]
Hmm strange, is this with a modified Dockerfile? current master build seems to not fail on it.

If you comment out the chekdupsym script does ffmpeg fail to link instead? if really both libssh.a and libzmq.a has a public sha1_init symbol it will probably fail. If this is the case a fix is to somehow rename one of them, maybe convince any of the upstreams to namespace it with som prefix.

**Comment by wader** [comment]
Aha you added libzmq. Try skip chekdupsym and see if it still fails. If so maybe do ugly patch for now that renames one of the symbols or make it private (static in c). But best would probably be to get one or both of the projects to fix it.

**Comment by wader** [comment]
Yeap seems so:
https://github.com/zeromq/libzmq/blob/b95d94935ed107679fd0ad9efd2f3d47309b6fd3/external/sha1/sha1.h#L68
https://github.com/canonical/libssh/blob/a09a5a5b5dd414bf422ab3ac3c50626eb46e8d67/include/libssh/wrapper.h#L79

**Comment by examedia-video-engineering** [comment]
> Aha you added libzmq. Try skip chekdupsym and see if it still fails. If so maybe do ugly patch for now that renames one of the symbols or make it private (static in c). But best would probably be to get one or both of the projects to fix it.

FFmpeg executes ok, but I'm not sure if it'll fail in a specific ZMQ use case... will do an "ugly patch" for zmq I guess. Thank you!

**Comment by examedia-video-engineering** [comment]
grep -r -l sha1_init * | xargs sed -i 's/sha1_init/zeromq_sha1_init/g' && \

seems to work for ZeroMQ :)
checkdupsym is now a PASS

**Comment by examedia-video-engineering** [comment]
grep -r -l sha1_init * | xargs sed -i 's/sha1_init/zeromq_sha1_init/g' && \

seems to work for ZeroMQ :)
checkdupsym is now a PASS

**Comment by wader** [comment]
Thanks! PR https://github.com/wader/static-ffmpeg/pull/502
