### ISSUE TITLE
Update ffmpeg version with bugfix

### ISSUE THREAD

**Issue by aokovic** [wader/static-ffmpeg#97]
Hello, 

i am using your project and recently i found a [bug](https://trac.ffmpeg.org/ticket/9369) on ffmpeg. Guys from ffmpeg comunity were so kind to fix it immediately and i now i need this version in your project.

Can you please add this version in your project ?

KR,

**Comment by wader** [comment]
Hi, i usually only build stable releases of ffmpeg for this repo so it will probable take while until that change reaches stable. I actually use a modified versions of this Dockerfile myself to be able to just this. It works something like this:

In in the Dockerfile just before building ffmpeg add this:
```Dockefile
COPY patches /patches/
```
and just after extracting ffmpeg add this:
```Dockerfile
  (test "$(echo /patches/*.patch)" = "/patches/*.patch" && true || \
    for f in /patches/*.patch ; do echo "$f" && patch -p1 < "$f" || exit 1; done) && \
```
then put own patches in `patches/`

By experience i know it can get a bit messy to support backporting patches from ffmpeg master to stable releases.

**Comment by aokovic** [comment]
Thanks, 
i understand you decision for using only stable versions. I will try to do something similar.

**Comment by wader** [comment]
👍  Hope the change reaches stable quite soon, and let me know if you have some questions how to use a modifier Dockerfile that can patch things

**Comment by wader** [comment]
OK to close?

**Comment by aokovic** [comment]
Yes, feel re to close this one.

Thanks
